import { createContext, useEffect, useState } from "react";

import { Routes, Route } from "react-router-dom"

import Home from "./pages/Home/Home.jsx"
import Catalog from "./pages/Catalog/Catalog.jsx"
import About from "./pages/About"
import Contacts from "./pages/Contacts"
import Product from "./pages/Product/Product.jsx"
import Cart from "./pages/Cart/Cart.jsx"

export const MainContext = createContext();

function Main() {

    const [data, setData] = useState([
        { id:1,
        name: 'High',
        imageTile: '/images/products/product_1.png',
        imagePage: '/images/products/page_product_1.png',
        category: 'Уход для лица',
        subcategory: 'Крем для лица',
        categoryFilter: 'creamFace',
        base:'true',
        countSize: '30',
        size: '30ml',
        price: '1000',
        description: 'Увлажняющий крем идеально подходит для повседневного ухода за молодой кожей. Крем равномерно распределяется по поверхности благодаря легкой текстуре, обеспечивает глубокое увлажнение, регенерацию клеток.',
        composition: 'Aqua, Cyclomethicone, Dicaprylyl Carbonate, Butylene Glycol, Glycerin, Tapioca Starch, Nelumbium Speciosum Flower Extract, Calendula Officinalis Flower Extract, Propylene Glycol, Tocopherol, Glycine Soja Oil, Dimethiconol, Citronellol, Limonene.',
        use: 'Нанесите крем на очищенную кожу лица легкими массажными круговыми движениями, избегая области вокруг глаз. Подходит для дневного и ночного ухода.' },
        { id:2,
        name: 'High',
        imageTile: '/images/products/product_1.png',
        imagePage: '/images/products/page_product_1.png',
        category: 'Уход для лица',
        subcategory: 'Крем для лица',
        categoryFilter: 'creamFace',
        base:'false',
        countSize: '50',
        size: '50ml',
        price: '1990',
        description: 'Увлажняющий крем идеально подходит для повседневного ухода за молодой кожей. Крем равномерно распределяется по поверхности благодаря легкой текстуре, обеспечивает глубокое увлажнение, регенерацию клеток.',
        composition: 'Aqua, Cyclomethicone, Dicaprylyl Carbonate, Butylene Glycol, Glycerin, Tapioca Starch, Nelumbium Speciosum Flower Extract, Calendula Officinalis Flower Extract, Propylene Glycol, Tocopherol, Glycine Soja Oil, Dimethiconol, Citronellol, Limonene.',
        use: 'Нанесите крем на очищенную кожу лица легкими массажными круговыми движениями, избегая области вокруг глаз. Подходит для дневного и ночного ухода.' },
        { id:3,
        name: 'Rest',
        imageTile: '/images/products/product_2.png',
        imagePage: '/images/products/page_product_1.png',
        category: 'Уход для лица',
        subcategory: 'Минеральная пудра',
        categoryFilter: 'powderFace',
        base:'true',
        countSize: '30',
        size: '30ml',
        price: '2000',
        description: 'Увлажняющий крем идеально подходит для повседневного ухода за молодой кожей. Крем равномерно распределяется по поверхности благодаря легкой текстуре, обеспечивает глубокое увлажнение, регенерацию клеток.',
        composition: 'Aqua, Cyclomethicone, Dicaprylyl Carbonate, Butylene Glycol, Glycerin, Tapioca Starch, Nelumbium Speciosum Flower Extract, Calendula Officinalis Flower Extract, Propylene Glycol, Tocopherol, Glycine Soja Oil, Dimethiconol, Citronellol, Limonene.',
        use: 'Нанесите крем на очищенную кожу лица легкими массажными круговыми движениями, избегая области вокруг глаз. Подходит для дневного и ночного ухода.' },
        { id:4,
        name: 'Rest',
        imageTile: '/images/products/product_2.png',
        imagePage: '/images/products/page_product_1.png',
        category: 'Уход для лица',
        subcategory: 'Минеральная пудра',
        categoryFilter: 'powderFace',
        base:'false',
        countSize: '50',
        size: '50ml',
        price: '2990',
        description: 'Увлажняющий крем идеально подходит для повседневного ухода за молодой кожей. Крем равномерно распределяется по поверхности благодаря легкой текстуре, обеспечивает глубокое увлажнение, регенерацию клеток.',
        composition: 'Aqua, Cyclomethicone, Dicaprylyl Carbonate, Butylene Glycol, Glycerin, Tapioca Starch, Nelumbium Speciosum Flower Extract, Calendula Officinalis Flower Extract, Propylene Glycol, Tocopherol, Glycine Soja Oil, Dimethiconol, Citronellol, Limonene.',
        use: 'Нанесите крем на очищенную кожу лица легкими массажными круговыми движениями, избегая области вокруг глаз. Подходит для дневного и ночного ухода.' },
        { id:5,
        name: 'Milk',
        imageTile: '/images/products/product_3.png',
        imagePage: '/images/products/page_product_1.png',
        category: 'Уход для тела',
        subcategory: 'Масло для тела',
        categoryFilter: 'oilBody',
        base:'true',
        countSize: '30',
        size: '30ml',
        price: '3000',
        description: 'Увлажняющий крем идеально подходит для повседневного ухода за молодой кожей. Крем равномерно распределяется по поверхности благодаря легкой текстуре, обеспечивает глубокое увлажнение, регенерацию клеток.',
        composition: 'Aqua, Cyclomethicone, Dicaprylyl Carbonate, Butylene Glycol, Glycerin, Tapioca Starch, Nelumbium Speciosum Flower Extract, Calendula Officinalis Flower Extract, Propylene Glycol, Tocopherol, Glycine Soja Oil, Dimethiconol, Citronellol, Limonene.',
        use: 'Нанесите крем на очищенную кожу лица легкими массажными круговыми движениями, избегая области вокруг глаз. Подходит для дневного и ночного ухода.' },
        { id:6,
        name: 'Milk',
        imageTile: '/images/products/product_3.png',
        imagePage: '/images/products/page_product_1.png',
        category: 'Уход для тела',
        subcategory: 'Масло для тела',
        categoryFilter: 'oilBody',
        base:'false',
        countSize: '70',
        size: '70ml',
        price: '3990',
        description: 'Увлажняющий крем идеально подходит для повседневного ухода за молодой кожей. Крем равномерно распределяется по поверхности благодаря легкой текстуре, обеспечивает глубокое увлажнение, регенерацию клеток.',
        composition: 'Aqua, Cyclomethicone, Dicaprylyl Carbonate, Butylene Glycol, Glycerin, Tapioca Starch, Nelumbium Speciosum Flower Extract, Calendula Officinalis Flower Extract, Propylene Glycol, Tocopherol, Glycine Soja Oil, Dimethiconol, Citronellol, Limonene.',
        use: 'Нанесите крем на очищенную кожу лица легкими массажными круговыми движениями, избегая области вокруг глаз. Подходит для дневного и ночного ухода.' },
        { id:7,
        name: 'Clean',
        imageTile: '/images/products/product_4.png',
        imagePage: '/images/products/page_product_1.png',
        category: 'Уход для лица',
        subcategory: 'Маска для лица',
        categoryFilter: 'maskFace',
        base:'true',
        countSize: '20',
        size: '20ml',
        price: '4000',
        description: 'Увлажняющий крем идеально подходит для повседневного ухода за молодой кожей. Крем равномерно распределяется по поверхности благодаря легкой текстуре, обеспечивает глубокое увлажнение, регенерацию клеток.',
        composition: 'Aqua, Cyclomethicone, Dicaprylyl Carbonate, Butylene Glycol, Glycerin, Tapioca Starch, Nelumbium Speciosum Flower Extract, Calendula Officinalis Flower Extract, Propylene Glycol, Tocopherol, Glycine Soja Oil, Dimethiconol, Citronellol, Limonene.',
        use: 'Нанесите крем на очищенную кожу лица легкими массажными круговыми движениями, избегая области вокруг глаз. Подходит для дневного и ночного ухода.' },
        { id:8,
        name: 'Clean',
        imageTile: '/images/products/product_4.png',
        imagePage: '/images/products/page_product_1.png',
        category: 'Уход для лица',
        subcategory: 'Маска для лица',
        categoryFilter: 'maskFace',
        base:'false',
        countSize: '50',
        size: '50ml',
        price: '4990',
        description: 'Увлажняющий крем идеально подходит для повседневного ухода за молодой кожей. Крем равномерно распределяется по поверхности благодаря легкой текстуре, обеспечивает глубокое увлажнение, регенерацию клеток.',
        composition: 'Aqua, Cyclomethicone, Dicaprylyl Carbonate, Butylene Glycol, Glycerin, Tapioca Starch, Nelumbium Speciosum Flower Extract, Calendula Officinalis Flower Extract, Propylene Glycol, Tocopherol, Glycine Soja Oil, Dimethiconol, Citronellol, Limonene.',
        use: 'Нанесите крем на очищенную кожу лица легкими массажными круговыми движениями, избегая области вокруг глаз. Подходит для дневного и ночного ухода.' },
        { id:9,
        name: 'Lotos',
        imageTile: '/images/products/product_5.png',
        imagePage: '/images/products/page_product_1.png',
        category: 'Уход для лица',
        subcategory: 'Маска для лица',
        categoryFilter: 'maskFace',
        base:'true',
        countSize: '55',
        size: '55ml',
        price: '5000',
        description: 'Увлажняющий крем идеально подходит для повседневного ухода за молодой кожей. Крем равномерно распределяется по поверхности благодаря легкой текстуре, обеспечивает глубокое увлажнение, регенерацию клеток.',
        composition: 'Aqua, Cyclomethicone, Dicaprylyl Carbonate, Butylene Glycol, Glycerin, Tapioca Starch, Nelumbium Speciosum Flower Extract, Calendula Officinalis Flower Extract, Propylene Glycol, Tocopherol, Glycine Soja Oil, Dimethiconol, Citronellol, Limonene.',
        use: 'Нанесите крем на очищенную кожу лица легкими массажными круговыми движениями, избегая области вокруг глаз. Подходит для дневного и ночного ухода.' },
        { id:10,
        name: 'Peony',
        imageTile: '/images/products/product_3.png',
        imagePage: '/images/products/page_product_1.png',
        category: 'Уход для тела',
        subcategory: 'Скраб для тела',
        categoryFilter: 'scrubBody',
        base:'true',
        countSize: '100',
        size: '100ml',
        price: '5000',
        description: 'Увлажняющий крем идеально подходит для повседневного ухода за молодой кожей. Крем равномерно распределяется по поверхности благодаря легкой текстуре, обеспечивает глубокое увлажнение, регенерацию клеток.',
        composition: 'Aqua, Cyclomethicone, Dicaprylyl Carbonate, Butylene Glycol, Glycerin, Tapioca Starch, Nelumbium Speciosum Flower Extract, Calendula Officinalis Flower Extract, Propylene Glycol, Tocopherol, Glycine Soja Oil, Dimethiconol, Citronellol, Limonene.',
        use: 'Нанесите крем на очищенную кожу лица легкими массажными круговыми движениями, избегая области вокруг глаз. Подходит для дневного и ночного ухода.' },
        { id:11,
        name: 'Peony',
        imageTile: '/images/products/product_3.png',
        imagePage: '/images/products/page_product_1.png',
        category: 'Уход для тела',
        subcategory: 'Скраб для тела',
        categoryFilter: 'scrubBody',
        base:'false',
        countSize: '200',
        size: '200ml',
        price: '9000',
        description: 'Увлажняющий крем идеально подходит для повседневного ухода за молодой кожей. Крем равномерно распределяется по поверхности благодаря легкой текстуре, обеспечивает глубокое увлажнение, регенерацию клеток.',
        composition: 'Aqua, Cyclomethicone, Dicaprylyl Carbonate, Butylene Glycol, Glycerin, Tapioca Starch, Nelumbium Speciosum Flower Extract, Calendula Officinalis Flower Extract, Propylene Glycol, Tocopherol, Glycine Soja Oil, Dimethiconol, Citronellol, Limonene.',
        use: 'Нанесите крем на очищенную кожу лица легкими массажными круговыми движениями, избегая области вокруг глаз. Подходит для дневного и ночного ухода.' },
        { id:12,
        name: 'Crocus',
        imageTile: '/images/products/product_5.png',
        imagePage: '/images/products/page_product_1.png',
        category: 'Уход для лица',
        subcategory: 'Тоник для лица',
        categoryFilter: 'tonicFace',
        base:'true',
        countSize: '100',
        size: '100ml',
        price: '3000',
        description: 'Увлажняющий крем идеально подходит для повседневного ухода за молодой кожей. Крем равномерно распределяется по поверхности благодаря легкой текстуре, обеспечивает глубокое увлажнение, регенерацию клеток.',
        composition: 'Aqua, Cyclomethicone, Dicaprylyl Carbonate, Butylene Glycol, Glycerin, Tapioca Starch, Nelumbium Speciosum Flower Extract, Calendula Officinalis Flower Extract, Propylene Glycol, Tocopherol, Glycine Soja Oil, Dimethiconol, Citronellol, Limonene.',
        use: 'Нанесите крем на очищенную кожу лица легкими массажными круговыми движениями, избегая области вокруг глаз. Подходит для дневного и ночного ухода.' },
        { id:13,
        name: 'Crocus',
        imageTile: '/images/products/product_5.png',
        imagePage: '/images/products/page_product_1.png',
        category: 'Уход для лица',
        subcategory: 'Тоник для лица',
        categoryFilter: 'tonicFace',
        base:'false',
        countSize: '200',
        size: '200ml',
        price: '5000',
        description: 'Увлажняющий крем идеально подходит для повседневного ухода за молодой кожей. Крем равномерно распределяется по поверхности благодаря легкой текстуре, обеспечивает глубокое увлажнение, регенерацию клеток.',
        composition: 'Aqua, Cyclomethicone, Dicaprylyl Carbonate, Butylene Glycol, Glycerin, Tapioca Starch, Nelumbium Speciosum Flower Extract, Calendula Officinalis Flower Extract, Propylene Glycol, Tocopherol, Glycine Soja Oil, Dimethiconol, Citronellol, Limonene.',
        use: 'Нанесите крем на очищенную кожу лица легкими массажными круговыми движениями, избегая области вокруг глаз. Подходит для дневного и ночного ухода.' },
        { id:14,
        name: 'Orchid',
        imageTile: '/images/products/product_3.png',
        imagePage: '/images/products/page_product_1.png',
        category: 'Уход для лица',
        subcategory: 'Минеральная пудра',
        categoryFilter: 'powderFace',
        base:'true',
        countSize: '30',
        size: '30ml',
        price: '3000',
        description: 'Увлажняющий крем идеально подходит для повседневного ухода за молодой кожей. Крем равномерно распределяется по поверхности благодаря легкой текстуре, обеспечивает глубокое увлажнение, регенерацию клеток.',
        composition: 'Aqua, Cyclomethicone, Dicaprylyl Carbonate, Butylene Glycol, Glycerin, Tapioca Starch, Nelumbium Speciosum Flower Extract, Calendula Officinalis Flower Extract, Propylene Glycol, Tocopherol, Glycine Soja Oil, Dimethiconol, Citronellol, Limonene.',
        use: 'Нанесите крем на очищенную кожу лица легкими массажными круговыми движениями, избегая области вокруг глаз. Подходит для дневного и ночного ухода.' },
        { id:15,
        name: 'Orchid',
        imageTile: '/images/products/product_3.png',
        imagePage: '/images/products/page_product_1.png',
        category: 'Уход для лица',
        subcategory: 'Минеральная пудра',
        categoryFilter: 'powderFace',
        base:'false',
        countSize: '50',
        size: '50ml',
        price: '5000',
        description: 'Увлажняющий крем идеально подходит для повседневного ухода за молодой кожей. Крем равномерно распределяется по поверхности благодаря легкой текстуре, обеспечивает глубокое увлажнение, регенерацию клеток.',
        composition: 'Aqua, Cyclomethicone, Dicaprylyl Carbonate, Butylene Glycol, Glycerin, Tapioca Starch, Nelumbium Speciosum Flower Extract, Calendula Officinalis Flower Extract, Propylene Glycol, Tocopherol, Glycine Soja Oil, Dimethiconol, Citronellol, Limonene.',
        use: 'Нанесите крем на очищенную кожу лица легкими массажными круговыми движениями, избегая области вокруг глаз. Подходит для дневного и ночного ухода.' },
        { id:16,
        name: 'Iris',
        imageTile: '/images/products/product_1.png',
        imagePage: '/images/products/page_product_1.png',
        category: 'Уход для тела',
        subcategory: 'Масло для тела',
        categoryFilter: 'oilBody',
        base:'true',
        countSize: '30',
        size: '30ml',
        price: '3000',
        description: 'Увлажняющий крем идеально подходит для повседневного ухода за молодой кожей. Крем равномерно распределяется по поверхности благодаря легкой текстуре, обеспечивает глубокое увлажнение, регенерацию клеток.',
        composition: 'Aqua, Cyclomethicone, Dicaprylyl Carbonate, Butylene Glycol, Glycerin, Tapioca Starch, Nelumbium Speciosum Flower Extract, Calendula Officinalis Flower Extract, Propylene Glycol, Tocopherol, Glycine Soja Oil, Dimethiconol, Citronellol, Limonene.',
        use: 'Нанесите крем на очищенную кожу лица легкими массажными круговыми движениями, избегая области вокруг глаз. Подходит для дневного и ночного ухода.' },
        { id:17,
        name: 'Iris',
        imageTile: '/images/products/product_1.png',
        imagePage: '/images/products/page_product_1.png',
        category: 'Уход для тела',
        subcategory: 'Масло для тела',
        categoryFilter: 'oilBody',
        base:'false',
        countSize: '70',
        size: '70ml',
        price: '5000',
        description: 'Увлажняющий крем идеально подходит для повседневного ухода за молодой кожей. Крем равномерно распределяется по поверхности благодаря легкой текстуре, обеспечивает глубокое увлажнение, регенерацию клеток.',
        composition: 'Aqua, Cyclomethicone, Dicaprylyl Carbonate, Butylene Glycol, Glycerin, Tapioca Starch, Nelumbium Speciosum Flower Extract, Calendula Officinalis Flower Extract, Propylene Glycol, Tocopherol, Glycine Soja Oil, Dimethiconol, Citronellol, Limonene.',
        use: 'Нанесите крем на очищенную кожу лица легкими массажными круговыми движениями, избегая области вокруг глаз. Подходит для дневного и ночного ухода.' },
        { id:18,
        name: 'Narcissus',
        imageTile: '/images/products/product_3.png',
        imagePage: '/images/products/page_product_1.png',
        category: 'Уход для лица',
        subcategory: 'Крем для лица',
        categoryFilter: 'creamFace',
        base:'true',
        countSize: '30',
        size: '30ml',
        price: '1000',
        description: 'Увлажняющий крем идеально подходит для повседневного ухода за молодой кожей. Крем равномерно распределяется по поверхности благодаря легкой текстуре, обеспечивает глубокое увлажнение, регенерацию клеток.',
        composition: 'Aqua, Cyclomethicone, Dicaprylyl Carbonate, Butylene Glycol, Glycerin, Tapioca Starch, Nelumbium Speciosum Flower Extract, Calendula Officinalis Flower Extract, Propylene Glycol, Tocopherol, Glycine Soja Oil, Dimethiconol, Citronellol, Limonene.',
        use: 'Нанесите крем на очищенную кожу лица легкими массажными круговыми движениями, избегая области вокруг глаз. Подходит для дневного и ночного ухода.' },
        { id:19,
        name: 'Narcissus',
        imageTile: '/images/products/product_3.png',
        imagePage: '/images/products/page_product_1.png',
        category: 'Уход для лица',
        subcategory: 'Крем для лица',
        categoryFilter: 'creamFace',
        base:'false',
        countSize: '50',
        size: '50ml',
        price: '1990',
        description: 'Увлажняющий крем идеально подходит для повседневного ухода за молодой кожей. Крем равномерно распределяется по поверхности благодаря легкой текстуре, обеспечивает глубокое увлажнение, регенерацию клеток.',
        composition: 'Aqua, Cyclomethicone, Dicaprylyl Carbonate, Butylene Glycol, Glycerin, Tapioca Starch, Nelumbium Speciosum Flower Extract, Calendula Officinalis Flower Extract, Propylene Glycol, Tocopherol, Glycine Soja Oil, Dimethiconol, Citronellol, Limonene.',
        use: 'Нанесите крем на очищенную кожу лица легкими массажными круговыми движениями, избегая области вокруг глаз. Подходит для дневного и ночного ухода.' },
        { id:20,
        name: 'Camomile',
        imageTile: '/images/products/product_5.png',
        imagePage: '/images/products/page_product_1.png',
        category: 'Уход для тела',
        subcategory: 'Крем для тела',
        categoryFilter: 'creamBody',
        base:'true',
        countSize: '30',
        size: '30ml',
        price: '1000',
        description: 'Увлажняющий крем идеально подходит для повседневного ухода за молодой кожей. Крем равномерно распределяется по поверхности благодаря легкой текстуре, обеспечивает глубокое увлажнение, регенерацию клеток.',
        composition: 'Aqua, Cyclomethicone, Dicaprylyl Carbonate, Butylene Glycol, Glycerin, Tapioca Starch, Nelumbium Speciosum Flower Extract, Calendula Officinalis Flower Extract, Propylene Glycol, Tocopherol, Glycine Soja Oil, Dimethiconol, Citronellol, Limonene.',
        use: 'Нанесите крем на очищенную кожу лица легкими массажными круговыми движениями, избегая области вокруг глаз. Подходит для дневного и ночного ухода.' },
        { id:21,
        name: 'Camomile',
        imageTile: '/images/products/product_5.png',
        imagePage: '/images/products/page_product_1.png',
        category: 'Уход для тела',
        subcategory: 'Крем для тела',
        categoryFilter: 'creamBody',
        base:'false',
        countSize: '50',
        size: '50ml',
        price: '1990',
        description: 'Увлажняющий крем идеально подходит для повседневного ухода за молодой кожей. Крем равномерно распределяется по поверхности благодаря легкой текстуре, обеспечивает глубокое увлажнение, регенерацию клеток.',
        composition: 'Aqua, Cyclomethicone, Dicaprylyl Carbonate, Butylene Glycol, Glycerin, Tapioca Starch, Nelumbium Speciosum Flower Extract, Calendula Officinalis Flower Extract, Propylene Glycol, Tocopherol, Glycine Soja Oil, Dimethiconol, Citronellol, Limonene.',
        use: 'Нанесите крем на очищенную кожу лица легкими массажными круговыми движениями, избегая области вокруг глаз. Подходит для дневного и ночного ухода.' },
        { id:22,
        name: 'Gerber',
        imageTile: '/images/products/product_4.png',
        imagePage: '/images/products/page_product_1.png',
        category: 'Уход для тела',
        subcategory: 'Скраб для тела',
        categoryFilter: 'scrubBody',
        base:'true',
        countSize: '100',
        size: '100ml',
        price: '5000',
        description: 'Увлажняющий крем идеально подходит для повседневного ухода за молодой кожей. Крем равномерно распределяется по поверхности благодаря легкой текстуре, обеспечивает глубокое увлажнение, регенерацию клеток.',
        composition: 'Aqua, Cyclomethicone, Dicaprylyl Carbonate, Butylene Glycol, Glycerin, Tapioca Starch, Nelumbium Speciosum Flower Extract, Calendula Officinalis Flower Extract, Propylene Glycol, Tocopherol, Glycine Soja Oil, Dimethiconol, Citronellol, Limonene.',
        use: 'Нанесите крем на очищенную кожу лица легкими массажными круговыми движениями, избегая области вокруг глаз. Подходит для дневного и ночного ухода.' },
        { id:23,
        name: 'Gerber',
        imageTile: '/images/products/product_4.png',
        imagePage: '/images/products/page_product_1.png',
        category: 'Уход для тела',
        subcategory: 'Скраб для тела',
        categoryFilter: 'scrubBody',
        base:'false',
        countSize: '200',
        size: '200ml',
        price: '9000',
        description: 'Увлажняющий крем идеально подходит для повседневного ухода за молодой кожей. Крем равномерно распределяется по поверхности благодаря легкой текстуре, обеспечивает глубокое увлажнение, регенерацию клеток.',
        composition: 'Aqua, Cyclomethicone, Dicaprylyl Carbonate, Butylene Glycol, Glycerin, Tapioca Starch, Nelumbium Speciosum Flower Extract, Calendula Officinalis Flower Extract, Propylene Glycol, Tocopherol, Glycine Soja Oil, Dimethiconol, Citronellol, Limonene.',
        use: 'Нанесите крем на очищенную кожу лица легкими массажными круговыми движениями, избегая области вокруг глаз. Подходит для дневного и ночного ухода.' },
        { id:24,
        name: 'Tonik',
        imageTile: '/images/products/product_4.png',
        imagePage: '/images/products/page_product_1.png',
        category: 'Уход для лица',
        subcategory: 'Тоник для лица',
        categoryFilter: 'tonicFace',
        base:'true',
        countSize: '100',
        size: '100ml',
        price: '3000',
        description: 'Увлажняющий крем идеально подходит для повседневного ухода за молодой кожей. Крем равномерно распределяется по поверхности благодаря легкой текстуре, обеспечивает глубокое увлажнение, регенерацию клеток.',
        composition: 'Aqua, Cyclomethicone, Dicaprylyl Carbonate, Butylene Glycol, Glycerin, Tapioca Starch, Nelumbium Speciosum Flower Extract, Calendula Officinalis Flower Extract, Propylene Glycol, Tocopherol, Glycine Soja Oil, Dimethiconol, Citronellol, Limonene.',
        use: 'Нанесите крем на очищенную кожу лица легкими массажными круговыми движениями, избегая области вокруг глаз. Подходит для дневного и ночного ухода.' },
        { id:25,
        name: 'Oil',
        imageTile: '/images/products/product_3.png',
        imagePage: '/images/products/page_product_1.png',
        category: 'Уход для тела',
        subcategory: 'Масло для тела',
        categoryFilter: 'oilBody',
        base:'true',
        countSize: '30',
        size: '30ml',
        price: '3000',
        description: 'Увлажняющий крем идеально подходит для повседневного ухода за молодой кожей. Крем равномерно распределяется по поверхности благодаря легкой текстуре, обеспечивает глубокое увлажнение, регенерацию клеток.',
        composition: 'Aqua, Cyclomethicone, Dicaprylyl Carbonate, Butylene Glycol, Glycerin, Tapioca Starch, Nelumbium Speciosum Flower Extract, Calendula Officinalis Flower Extract, Propylene Glycol, Tocopherol, Glycine Soja Oil, Dimethiconol, Citronellol, Limonene.',
        use: 'Нанесите крем на очищенную кожу лица легкими массажными круговыми движениями, избегая области вокруг глаз. Подходит для дневного и ночного ухода.' },
        { id:26,
        name: 'Oil',
        imageTile: '/images/products/product_3.png',
        imagePage: '/images/products/page_product_1.png',
        category: 'Уход для тела',
        subcategory: 'Масло для тела',
        categoryFilter: 'oilBody',
        base:'false',
        countSize: '70',
        size: '70ml',
        price: '3990',
        description: 'Увлажняющий крем идеально подходит для повседневного ухода за молодой кожей. Крем равномерно распределяется по поверхности благодаря легкой текстуре, обеспечивает глубокое увлажнение, регенерацию клеток.',
        composition: 'Aqua, Cyclomethicone, Dicaprylyl Carbonate, Butylene Glycol, Glycerin, Tapioca Starch, Nelumbium Speciosum Flower Extract, Calendula Officinalis Flower Extract, Propylene Glycol, Tocopherol, Glycine Soja Oil, Dimethiconol, Citronellol, Limonene.',
        use: 'Нанесите крем на очищенную кожу лица легкими массажными круговыми движениями, избегая области вокруг глаз. Подходит для дневного и ночного ухода.' },
        { id:27,
        name: 'Violet',
        imageTile: '/images/products/product_4.png',
        imagePage: '/images/products/page_product_1.png',
        category: 'Уход для лица',
        subcategory: 'Крем для лица',
        categoryFilter: 'creamFace',
        base:'true',
        countSize: '30',
        size: '30ml',
        price: '1000',
        description: 'Увлажняющий крем идеально подходит для повседневного ухода за молодой кожей. Крем равномерно распределяется по поверхности благодаря легкой текстуре, обеспечивает глубокое увлажнение, регенерацию клеток.',
        composition: 'Aqua, Cyclomethicone, Dicaprylyl Carbonate, Butylene Glycol, Glycerin, Tapioca Starch, Nelumbium Speciosum Flower Extract, Calendula Officinalis Flower Extract, Propylene Glycol, Tocopherol, Glycine Soja Oil, Dimethiconol, Citronellol, Limonene.',
        use: 'Нанесите крем на очищенную кожу лица легкими массажными круговыми движениями, избегая области вокруг глаз. Подходит для дневного и ночного ухода.' },
        { id:28,
        name: 'Violet',
        imageTile: '/images/products/product_4.png',
        imagePage: '/images/products/page_product_1.png',
        category: 'Уход для лица',
        subcategory: 'Крем для лица',
        categoryFilter: 'creamFace',
        base:'false',
        countSize: '50',
        size: '50ml',
        price: '1990',
        description: 'Увлажняющий крем идеально подходит для повседневного ухода за молодой кожей. Крем равномерно распределяется по поверхности благодаря легкой текстуре, обеспечивает глубокое увлажнение, регенерацию клеток.',
        composition: 'Aqua, Cyclomethicone, Dicaprylyl Carbonate, Butylene Glycol, Glycerin, Tapioca Starch, Nelumbium Speciosum Flower Extract, Calendula Officinalis Flower Extract, Propylene Glycol, Tocopherol, Glycine Soja Oil, Dimethiconol, Citronellol, Limonene.',
        use: 'Нанесите крем на очищенную кожу лица легкими массажными круговыми движениями, избегая области вокруг глаз. Подходит для дневного и ночного ухода.' },
        { id:29,
        name: 'Lavender',
        imageTile: '/images/products/product_2.png',
        imagePage: '/images/products/page_product_1.png',
        category: 'Уход для тела',
        subcategory: 'Крем для тела',
        categoryFilter: 'creamBody',
        base:'true',
        countSize: '30',
        size: '30ml',
        price: '1000',
        description: 'Увлажняющий крем идеально подходит для повседневного ухода за молодой кожей. Крем равномерно распределяется по поверхности благодаря легкой текстуре, обеспечивает глубокое увлажнение, регенерацию клеток.',
        composition: 'Aqua, Cyclomethicone, Dicaprylyl Carbonate, Butylene Glycol, Glycerin, Tapioca Starch, Nelumbium Speciosum Flower Extract, Calendula Officinalis Flower Extract, Propylene Glycol, Tocopherol, Glycine Soja Oil, Dimethiconol, Citronellol, Limonene.',
        use: 'Нанесите крем на очищенную кожу лица легкими массажными круговыми движениями, избегая области вокруг глаз. Подходит для дневного и ночного ухода.' },
        { id:30,
        name: 'Lavender',
        imageTile: '/images/products/product_2.png',
        imagePage: '/images/products/page_product_1.png',
        category: 'Уход для тела',
        subcategory: 'Крем для тела',
        categoryFilter: 'creamBody',
        base:'false',
        countSize: '50',
        size: '50ml',
        price: '1990',
        description: 'Увлажняющий крем идеально подходит для повседневного ухода за молодой кожей. Крем равномерно распределяется по поверхности благодаря легкой текстуре, обеспечивает глубокое увлажнение, регенерацию клеток.',
        composition: 'Aqua, Cyclomethicone, Dicaprylyl Carbonate, Butylene Glycol, Glycerin, Tapioca Starch, Nelumbium Speciosum Flower Extract, Calendula Officinalis Flower Extract, Propylene Glycol, Tocopherol, Glycine Soja Oil, Dimethiconol, Citronellol, Limonene.',
        use: 'Нанесите крем на очищенную кожу лица легкими массажными круговыми движениями, избегая области вокруг глаз. Подходит для дневного и ночного ухода.' },
    ])

    // const getData = async () => {
    //     const dataServer = await fetch('https://fakestoreapi.com/products')
    //     .then(response => response.json());

    //     localStorage.setItem('data', JSON.stringify(dataServer));
    //     setData([...dataServer]);
    // };

    useEffect(() => {
        if (data.length == 0) {
            let dataLocal = localStorage.getItem('data');
            dataLocal = JSON.parse(dataLocal);

            // if (dataLocal && dataLocal.length > 0) {
            //     setData([...dataLocal]);
            // } else {
            //     getData();
            // }
        }

    }, [data]);


	return (
        <MainContext.Provider value={data}>
        <main className="main">
        <Routes>
            <Route path="/" element={<Home/>}/>
            <Route path="/catalog/" element={<Catalog/>}/>
            <Route path="/about/" element={<About/>}/>
            <Route path="/contacts/" element={<Contacts/>}/>
            <Route path="/product/:product_id/" element={<Product/>}/>
            <Route path="/product/:product_category/" element={<Catalog/>}/>
            <Route path="/product/:product_category/:product_id" element={<Product/>}/>
            <Route path="/cart/" element={<Cart/>}/>
        </Routes>
        </main>
        </MainContext.Provider>
	)
}

export default Main
